[package]
name = "csv_tui"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
csv = "1.2.1"
tui = "0.19.0"
